os: linux
sudo: required
dist: trusty
language: c
compiler:
  - gcc

branches:
  only:
    - master
    - coverity

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "oUaboO/D5Q/tujtoGEzYFdT5xKD7VJfAqfiSLEoztv5xS2ycwmw/NFJ+3JFLYD6x23/0fjvCU/wKZ3Qyyd9VAxMyQDBkBK0aLcc6kC8fr8ECFyHazd86TCux3TOVGoAe/2IpTFE1VlqpjEKUhLAnsKHGgspLrYJ5SBUVAeWKnkpk5Kwt8Vyghz6Gir8LrVkqKEA7eGXqklDlwhExMnlyehLHMd4ZeFrCC1vI3g/ZoJJzhAvn1VSgPhMXamTi+EpHkEThpNsic7ZMmYb+tshLXjaQxIORpokcB/TIsaNFP/P5fIAtRkJXKNHapXC1lrgTRnNZHzJ6FzCrIAce/l3DChCAqTfu3WNrH885eqe6U4HbBeG7Gt2es86rTe9vPfYSuAIwQLqEFpkNfq4HtEu5CSAUXxwtGXeq3FAJrpJqsZ/8UX383ZVik0Gksw3XIdKbkjI5M1gWE/rLanK9+ZXECcBwsn7EW1lgE66LmZacX3q5WnybC1hKt+FffBfLYvubFV8X9XYolEJ6NwVvGdjTUhvNzPTYZdtWoP7WWyQwM/SBHQHkAqbqiyUQGZrkHpmsz4ohmrkLVCnOIuoEd8YeTvIIXGS0z400zbLqkHwDmATP3sRQA6pfPQfRpKz/9HaZf4kUk1MFtDHyWNo0t/XEDKKLnOzHsRbZD0LLqJHcKuQ="
   - PYTHONPATH=/usr/lib/python2.7/site-packages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-multilib
      - gcc
      - g++
      - autoconf
      - pkg-config
      - make
      - automake
      - libxml2-dev
      - libxml2
      - git
      - python
      - python-setuptools
      - python-dev
      - libpcap-dev
  coverity_scan:
    project:
      name: "CESNET/Nemea-Modules"
      description: "Build submitted via Travis CI"
    notification_email: cejkat@cesnet.cz
    build_command_prepend: "./bootstrap.sh && ./configure -q && make clean"
    build_command:   "make -j5"
    branch_pattern: coverity

before_install:
   - pyenv global 2.7.13
   - export PATH=$(pyenv prefix)/bin:$PATH
   - ( git clone --depth 2 -q https://github.com/CESNET/nemea-framework nf; cd nf; ./bootstrap.sh && ./configure -q --prefix=/usr --bindir=/usr/bin/nemea && make -j10 && sudo make install; (cd pytrap && $(pyenv which python) setup.py install;); (cd pycommon && $(pyenv which python) setup.py install;); )
   - sudo rm -rf nemea-framework
   - python -c 'import pytrap'
   - grep -e '\<22/tcp' -e '\<23/tcp' -e '\<2179/tcp' -e '\<5900/tcp' /etc/services

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - ./bootstrap.sh && ./configure && make check || { find . \( -name '*.sh.log' -o -name '*.test.log' -o -name '*.trs' \) -print -exec cat {} \;; exit 1; } && make distcheck
  - mkdir dist-pkgs && cp *.spec *.tar.gz dist-pkgs && (cd dist-pkgs/"$d"; tar --strip-components=1 -xf *.tar.gz;)
  - ./configure -q --enable-debug CXXFLAGS=-coverage CFLAGS=-coverage LDFLAGS=-lgcov && make clean && make check

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist-pkgs
  github_token: $GITHUB_TOKEN
  target_branch: dist-packages
  on:
    branch: master

