os: linux
sudo: required
dist: trusty
language: c
compiler:
  - gcc

branches:
  only:
    - master
    - coverity

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "oUaboO/D5Q/tujtoGEzYFdT5xKD7VJfAqfiSLEoztv5xS2ycwmw/NFJ+3JFLYD6x23/0fjvCU/wKZ3Qyyd9VAxMyQDBkBK0aLcc6kC8fr8ECFyHazd86TCux3TOVGoAe/2IpTFE1VlqpjEKUhLAnsKHGgspLrYJ5SBUVAeWKnkpk5Kwt8Vyghz6Gir8LrVkqKEA7eGXqklDlwhExMnlyehLHMd4ZeFrCC1vI3g/ZoJJzhAvn1VSgPhMXamTi+EpHkEThpNsic7ZMmYb+tshLXjaQxIORpokcB/TIsaNFP/P5fIAtRkJXKNHapXC1lrgTRnNZHzJ6FzCrIAce/l3DChCAqTfu3WNrH885eqe6U4HbBeG7Gt2es86rTe9vPfYSuAIwQLqEFpkNfq4HtEu5CSAUXxwtGXeq3FAJrpJqsZ/8UX383ZVik0Gksw3XIdKbkjI5M1gWE/rLanK9+ZXECcBwsn7EW1lgE66LmZacX3q5WnybC1hKt+FffBfLYvubFV8X9XYolEJ6NwVvGdjTUhvNzPTYZdtWoP7WWyQwM/SBHQHkAqbqiyUQGZrkHpmsz4ohmrkLVCnOIuoEd8YeTvIIXGS0z400zbLqkHwDmATP3sRQA6pfPQfRpKz/9HaZf4kUk1MFtDHyWNo0t/XEDKKLnOzHsRbZD0LLqJHcKuQ="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-multilib
      - gcc-c++
      - autoconf
      - pkg-config
      - make
      - automake
      - libxml2-devel
      - libxml2
  coverity_scan:
    project:
      name: "CESNET/Nemea-Modules"
      description: "Build submitted via Travis CI"
    notification_email: cejkat@cesnet.cz
    build_command_prepend: "./bootstrap.sh && ./configure -q && make clean"
    build_command:   "make -j5"
    branch_pattern: coverity

before_install:
   - ( git clone --depth 1 -q https://github.com/CESNET/nemea-framework; cd nemea-framework; ./bootstrap.sh && ./configure -q --prefix=/usr --bindir=/usr/bin/nemea && make -j10 && sudo make install; (cd python && sudo python setup.py install --prefix=/usr;); (cd pycommon && sudo python setup.py install --prefix=/usr;); )

script:
  - ls -ld /usr/lib/python*/site-packages/*
  - ./bootstrap.sh && ./configure --disable-repobuild && make check || { find . \( -name '*.log' -o -name '*.trs' \) -print -exec cat {} \;; exit 1; }

